name: project_root
repository: https://github.com/rbdog/templates/flutter_mobile_app
packages:
  - main
  - feature_app_update
  - feature_auth
  - feature_debug_log
  - feature_flavor
  - feature_market_analytics
  - feature_router
  - feature_theme
  - feature_todo
  - feature_user

# melos clean
# melos bootstrap
# melos analyze
# melos format
# melos publish --no-dry-run
# melos run

command:
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
  bootstrap:
    hooks:
      post: |
        melos exec --flutter --dir-exists=lib/l10n -- "flutter gen-l10n --arb-dir=scripts/l10n"
        dart run build_runner build --delete-conflicting-outputs

# VSCode - Command Pallete
# Melos: Show package graph
