name: mobile_app
description: A mobile app project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

# パッケージ一覧
dependencies:
  flutter: # フレームワーク本体
    sdk: flutter
  flutter_localizations: # 多言語
    sdk: flutter
  intl: # 国際化
  uuid: # ID生成
  package_info_plus: # アプリバージョン
  flutter_riverpod: # 状態管理 - グローバル
  flutter_hooks: # 状態管理 -ローカル
  go_router: # 画面遷移
  freezed_annotation: # 不変インスタンス作成

dev_dependencies:
  freezed: # 不変インスタンス作成 コマンド
  build_runner: # コード生成
  flutter_test: # テスト
    sdk: flutter
  flutter_lints: ^4.0.0 # 静的解析
  import_sorter: # インポート並び替え

flutter:
  generate: true # gen-l10n コマンドを有効化
  uses-material-design: true
  assets:
    - assets/fonts/OFL.txt
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
