melos version \
  --all \
  --message="NEW" \
  --no-changelog \
  --no-git-tag-version \
  --no-git-commit-version \
  --manual-version=mobile_app:major \
  --manual-version=feature_app_update:major \
  --manual-version=feature_auth:major \
  --manual-version=feature_debug_log:major \
  --manual-version=feature_flavor:major \
  --manual-version=feature_market_analytics:major \
  --manual-version=feature_router:major \
  --manual-version=feature_theme:major \
  --manual-version=feature_todo:major \
  --manual-version=feature_user:major \
