melos version \
  --all \
  --message="NEW" \
  --no-changelog \
  --no-git-tag-version \
  --no-git-commit-version \
  --manual-version=mobile_app:minor \
  --manual-version=feature_app_update:minor \
  --manual-version=feature_auth:minor \
  --manual-version=feature_debug_log:minor \
  --manual-version=feature_flavor:minor \
  --manual-version=feature_market_analytics:minor \
  --manual-version=feature_router:minor \
  --manual-version=feature_theme:minor \
  --manual-version=feature_todo:minor \
  --manual-version=feature_user:minor \
