name: feature_market_analytics
description: A Feature
publish_to: "none"
version: 0.10.0

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

# パッケージ一覧
dependencies:
  riverpod:
  firebase_analytics:

  feature_flavor:
    path: ../feature_flavor/

dev_dependencies:
  flutter_test: # テスト
    sdk: flutter
  flutter_lints: ^4.0.0 # 静的解析
  import_sorter: # インポート並び替え

flutter:
  generate: true # gen-l10n コマンドを有効化
  uses-material-design: false
