name: feature_theme
description: A new Flutter project.
publish_to: "none"
version: 0.9.0

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

# パッケージ一覧
dependencies:
  flutter: # フレームワーク本体
    sdk: flutter
  flutter_localizations: # 多言語
    sdk: flutter
  intl: # 国際化

dev_dependencies:
  flutter_test: # テスト
    sdk: flutter
  flutter_lints: ^4.0.0 # 静的解析
  import_sorter: # インポート並び替え

flutter:
  generate: true # gen-l10n コマンドを有効化
  uses-material-design: true
